apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 3
  selector:
    app: kubia-rc
  template:
    metadata:
      name: kubia-rc
      labels:
        app: kubia-rc
    spec:
      containers:
      - name: mycontainer
        image: zhou19539/myrep
        ports:
        - containerPort: 80
